import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[shell]
program = "/usr/bin/bash"

#[colors]
#draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 10
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
#bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
#italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "CopySelection"
key = "F1"

[[keyboard.bindings]]
action = "PasteSelection"
key = "F2"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift"

[mouse]
hide_when_typing = true

[window]
opacity = 0.9
padding = { x = 10, y = 10 }
