icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $max"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $used / $total "
[[block.click]]
button = "right"
update = true

[[block]]
block = "hueshift"
format = "  $temperature "
click_temp = 4000

[[block]]
block = "kdeconnect"
[[block.click]]
button = "left"
cmd = "kdeconnect-app"

[[block]]
block = "sound"
max_vol = 150
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "dnf"
interval = 1800
format = " $icon $count.eng(w:1) "
format_singular = " $icon "
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
[[block.click]]
button = "left"
cmd = "dnf list -q --upgrades | tail -n +2 | rofi -dmenu"
[[block.click]]
button = "right"
update = true

[[block]]
block = "docker"
if_command = "0"
[[block.click]]
button = "left"
cmd = "docker ps -a --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}' | rofi -dmenu"

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
short = " $icon $timestamp.datetime(f:'%R') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "right"
action = "show"

[[block]]
block = "tea_timer"
format = " $icon {$hours:$minutes:$seconds |}"
increment = 60
done_cmd = "notify-send 'Timer Finished'"

