icons_format = "{icon}"

[theme]
theme = "dracula"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $max"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "docker"

[[block]]
block = "dnf"
interval = 1800
format = " $icon $count.eng(w:1) "
format_singular = " $icon "
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

