# .bashrc

[[ $- == *i* ]] && source ~/.local/share/blesh/ble.sh --noattach

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if type -P javac > /dev/null; then
  export JAVA_HOME="/usr/lib/jvm/java-openjdk"
  export PATH="$JAVA_HOME/bin:$PATH"
fi

if type -P rustup > /dev/null; then
    \. "$HOME/.cargo/env"
    source <( rustup completions bash )          # for rustup
    source <( rustup completions bash cargo )    # for cargo
fi

bind 'set completion-ignore-case on'

if type -P starship > /dev/null; then eval "$(starship init bash)"; fi

if type -P zoxide > /dev/null; then eval "$(zoxide init bash)"; fi

if type -P atuin > /dev/null; then eval "$(atuin init bash)"; fi

[[ ${BLE_VERSION-} ]] && ble-attach
