#!/usr/bin/env bash

#### INTERNAL HELPERS ####

# Adds a directory to PATH only if it exists and isn't already present.
# This prevents PATH bloating during subshell spawning.
safe_path_add() {
  [[ -d "$1" ]] && [[ ":$PATH:" != *":$1:"* ]] && export PATH="$1:$PATH"
}

#### CORE PATHS & BINARIES ####

# Local user binaries (Scripts, Go bins, etc.)
safe_path_add "$HOME/.local/bin"

# Neovim (AppImage or Manual Install)
[[ -d "/opt/nvim-linux-x86_64/bin" ]] && export PATH="$PATH:/opt/nvim-linux-x86_64/bin"

#### RUST / CARGO CONFIGURATION ####

if [[ -d "$HOME/.cargo" ]]; then
  # Load Cargo environment variables
  . "$HOME/.cargo/env"

  # Load pre-generated completions from local storage (optimized performance)
  # Note: These are generated by the 'updates' script during 'rust_u'
  COMP_DIR="$HOME/.local/share/bash-completion/completions"
  [[ -f "$COMP_DIR/rustup" ]] && . "$COMP_DIR/rustup"
  [[ -f "$COMP_DIR/cargo" ]] && . "$COMP_DIR/cargo"
fi

#### NVM (LAZY LOADING) ####

# Initialize NVM only when a related command is executed to keep shell startup fast
if [[ -d "$HOME/.nvm" ]]; then
  export NVM_DIR="$HOME/.nvm"

  # Unified loader: Sources NVM environment and completions in one pass
  load_nvm() {
    # Immediate unset to prevent infinite recursion during command execution
    unset -f nvm node npm npx nvim

    # Source core NVM logic and bash completions
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  }

  # Define triggers for binary interception
  nvm() {
    load_nvm
    nvm "$@"
  }
  node() {
    load_nvm
    node "$@"
  }
  npm() {
    load_nvm
    npm "$@"
  }
  npx() {
    load_nvm
    npx "$@"
  }

  # Ensure Node is available for LSPs/Mason when launching Neovim
  nvim() {
    load_nvm
    command nvim "$@"
  }
fi

#### JAVA DEVELOPMENT ####

# Dynamic JAVA_HOME detection based on distribution standards
if command -v javac &>/dev/null; then
  if command -v apt &>/dev/null; then
    # Debian/Ubuntu Standard
    export JAVA_HOME="/usr/lib/jvm/default-java"
  elif command -v dnf &>/dev/null; then
    # Fedora/RHEL Standard (Search for Temurin or OpenJDK)
    for jdk in /usr/lib/jvm/*; do
      if [[ "$jdk" == *temurin* || "$jdk" == *java-openjdk* ]]; then
        export JAVA_HOME="$jdk"
        break
      fi
    done
  fi
  [[ -n "$JAVA_HOME" ]] && safe_path_add "$JAVA_HOME/bin"
fi

#### GOLANG CONFIGURATION ####

if command -v go &>/dev/null; then
  export GOPATH="$HOME/.go"
  safe_path_add "$GOPATH/bin"
  safe_path_add "/usr/local/go/bin"
fi

#### CONTAINERIZATION (PODMAN/DOCKER) ####

# Rootless Podman socket configuration for Docker-compatible tools
if command -v podman &>/dev/null; then
  # export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
  export DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock
  if command -v kind &>/dev/null; then
    export KIND_EXPERIMENTAL_PROVIDER=podman
  fi
fi

#### INTERACTIVE SHELL IMPROVEMENTS ####

# Only execute these in interactive Bash sessions
if [[ -n "$PS1" && "$(readlink /proc/$$/exe)" == *"/bash" ]]; then
  # Case-insensitive tab completion
  bind 'set completion-ignore-case on'

  # Modern Tool Initializations
  command -v starship &>/dev/null && eval "$(starship init bash)"
  command -v zoxide &>/dev/null && eval "$(zoxide init bash)"
  command -v fzf &>/dev/null && eval "$(fzf --bash)"
fi

#### CLEANUP ####

# Remove the helper function from the environment to keep it clean
unset -f safe_path_add
