#!/bin/bash
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
yellowColour="\e[0;33m\033[1m"
update() {
  NVM_VERSION=$(nvm current)
  (
    cd "$NVM_DIR"
    git fetch --tags origin
    git checkout $(git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1))
  ) && \. "$NVM_DIR/nvm.sh"
  echo -e "${greenColour}Checking for possible nvm updates...${endColour}"
  if [ ! "$(nvm ls-remote --no-colors | tail -n1 | awk '{print $2}')" = "$(nvm current)" ]; then
    echo -e "${yellowColour}NVM update found${endColour}"
    nvm install node
    nvm reinstall-packages "$NVM_VERSION"
  fi

  if [[ $(which nvim) != "/snap/bin/nvim" ]]; then
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    if [ ! "$(md5sum ~/portable/nvim.appimage | awk '{print $1}')" = "$(md5sum "$HOME/nvim.appimage" | awk '{print $1}')" ]; then
      echo -e "${yellowColour}Neovim update found!${endColour}"
      chmod u+x nvim.appimage
      rm ~/portable/nvim.appimage
      mv "$HOME/nvim.appimage" ~/portable/
    else
      echo "Nothing to do."
      rm nvim.appimage
    fi
  fi

  if [ -d "$HOME/.cargo" ]; then
    echo -e "${greenColour}Updating rust...${endColour}"
    rustup update
    ## The construction process can take a long time dependColouring on the capacity of the machine.
    ## It is convenient to ask before doing this action.
    while true; do
      echo -ne "${yellowColour}Update installed binaries by cargo? (y/n) -> ${endColour}" && read -r opt
      if [ "$(echo "$opt" | awk '{print tolower($0)}')" = "y" ]; then
        for bin in $(cargo install --list | awk '/^ / {print}' | tr -d ' '); do
          cargo install "$bin" --force
        done
        break
      elif [ "$(echo "$opt" | awk '{print tolower($0)}')" = "n" ]; then
        break
      fi
    done
  fi

  if [ "$(
    which apt &>/dev/null
    echo $?
  )" -eq 0 ]; then
    echo -e "${greenColour}Updating operating system...${endColour}"
    sudo apt-get update && sudo apt-get upgrade -y
    sudo apt-get autoremove -y
    echo -e "${greenColour}Checking for snap package updates if they exist...${endColour}"
    [[ -d /snap ]] && sudo snap refresh
  fi

  OHMZ=$HOME/.ohmyzsh
  if [[ -d $OHMZ ]]; then
    cd "$OHMZ" || return 1
    echo -e "${greenColour}Checking for updates to oh my zsh framework...${endColour}"
    git pull --rebase
    cd || return 1
  fi

  P10K=$HOME/.powerlevel10k
  if [[ -d $P10K ]]; then
    cd "$P10K" || return 1
    echo -e "${greenColour}Checking for updates to powerlevel10k...${endColour}"
    git pull --rebase
    cd || return 1
  fi

  THEME=$HOME/.dracula
  if [[ -d $THEME ]]; then
    cd "$THEME" || return 1
    echo -e "${greenColour}Checking for updates to all dracula color schemes...${endColour}"
    for DIR in *; do
      cd "$DIR" || return 1
      git pull --rebase
      cd .. || return 1
    done
    sudo rm -rf /boot/grub/themes/dracula
    sudo cp -r ~/.dracula/grub/dracula /boot/grub/themes/
    cd || return 1
  fi

  if [[ $(which starship) == "/usr/local/bin/starship" ]]; then
    echo -e "${greenColour}Updating starship...${endColour}"
    curl -sS https://starship.rs/install.sh | sudo sh
  fi

}
